### ISSUE TITLE
How to drastically reduce Umikaze boot time [SOLUTION]

### ISSUE THREAD

**Issue by manbehindthemadness** [intelligent-agent/Refactor#105]
I have been looking over the boot performance of the latest stable image:
root@kamikaze: systemd-analyze blame
    4min 39.354s networking.service
    4min 37.420s generic-board-startup.service
         25.693s dev-mmcblk1p1.device
          7.441s nmbd.service
          5.650s samba-ad-dc.service
          5.379s NetworkManager-wait-online.service
          5.200s smbd.service
          3.853s loadcpufreq.service
          3.354s systemd-logind.service
          3.057s console-setup.service
          2.980s netfilter-persistent.service
          2.883s dnsmasq.service
          2.243s udhcpd.service
          2.233s systemd-udev-trigger.service
          2.215s NetworkManager.service
          1.442s bb-wl18xx-wlan0.service
          1.428s systemd-user-sessions.service
          1.189s rsyslog.service
           756ms avahi-daemon.service
           706ms systemd-udevd.service
           687ms systemd-journald.service
           630ms keyboard-setup.service
           620ms cpufrequtils.service
           616ms polkitd.service
           610ms systemd-journal-flush.service
           570ms pppd-dns.service
           555ms user@1002.service
           512ms resolvconf.service
           494ms capemgr.service
           493ms systemd-timesyncd.service
           411ms systemd-update-utmp.service
           389ms systemd-modules-load.service
           382ms kmod-static-nodes.service
root@kamikaze:~# systemd-analyze time
Startup finished in 8.769s (kernel) + 4min 55.570s (userspace) = 5min 4.340s
root@kamikaze:~# systemd-analyze critical-chain
The time after the unit is active or started is printed after the "@" character.
The time the unit takes to start is printed after the "+" character.
graphical.target @4min 55.420s
└─multi-user.target @4min 55.414s
  └─smbd.service @4min 50.197s +5.200s
    └─nmbd.service @4min 42.731s +7.441s
      └─network-online.target @4min 42.684s
        └─network.target @4min 42.669s
          └─wpa_supplicant.service @34.858s +225ms
            └─basic.target @4.594s
              └─sockets.target @4.582s
                └─acpid.socket @4.571s
                  └─sysinit.target @4.440s
                    └─systemd-udev-trigger.service @2.193s +2.233s
                      └─systemd-journald.socket @939ms
                        └─-.slice @588ms
It's plain to see that we are suffering from two services blocking proper boot up.
Solution:
Alter the network startup timeout by changing TimeoutStartSec=5min to TimeoutStartSec=5s within /etc/systemd/system/network-online.target.wants/networking.service
Disable USB Flash my uncommenting USB_IMAGE_FILE_DISABLED=yes from /etc/default/bb-boot
Results:
root@kamikaze: systemd-analyze blame
         35.956s generic-board-startup.service
         33.042s dev-mmcblk1p1.device
         14.517s nmbd.service
         12.554s samba-ad-dc.service
         10.552s smbd.service
          5.477s NetworkManager-wait-online.service
          5.077s networking.service
          4.687s dnsmasq.service
          4.255s loadcpufreq.service
          3.992s systemd-logind.service
          3.456s netfilter-persistent.service
          3.445s console-setup.service
          2.577s NetworkManager.service
          2.327s systemd-udev-trigger.service
          1.878s bb-wl18xx-wlan0.service
          1.849s udhcpd.service
          1.601s pppd-dns.service
          1.557s capemgr.service
          1.493s systemd-user-sessions.service
          1.278s avahi-daemon.service
          1.199s rsyslog.service
           912ms user@1002.service
           806ms ssh.service
           793ms systemd-udevd.service
           676ms keyboard-setup.service
           650ms polkitd.service
           623ms systemd-journal-flush.service
           618ms cpufrequtils.service
           581ms systemd-journald.service
           564ms kmod-static-nodes.service
           416ms systemd-timesyncd.service
           409ms systemd-modules-load.service
           394ms sys-kernel-debug.mount
           361ms systemd-rfkill.service
           349ms resolvconf.service
           341ms systemd-random-seed.service
           335ms setvtrgb.service
           328ms systemd-update-utmp.service
           325ms systemd-sysctl.service
           270ms systemd-tmpfiles-setup.service
           252ms user@0.service
           226ms dev-mqueue.mount
           220ms wpa_supplicant.service
           195ms sys-kernel-config.mount
           188ms systemd-update-utmp-runlevel.service
           186ms bb-wl18xx-bluetooth.service
           179ms systemd-remount-fs.service
           178ms systemd-tmpfiles-setup-dev.service
           140ms sys-fs-fuse-connections.mount
           110ms rc-local.service
Startup finished in 8.317s (kernel) + 1min 30.769s (userspace) = 1min 39.087s
root@kamikaze:~# systemd-analyze critical-chain
The time after the unit is active or started is printed after the "@" character.
The time the unit takes to start is printed after the "+" character.
graphical.target @41.155s
└─multi-user.target @41.144s
  └─smbd.service @29.010s +10.552s
    └─nmbd.service @14.426s +14.517s
      └─network-online.target @14.385s
        └─NetworkManager-wait-online.service @8.880s +5.477s
          └─NetworkManager.service @6.109s +2.577s
            └─dbus.service @5.449s
              └─basic.target @4.626s
                └─sockets.target @4.614s
                  └─dbus.socket @4.599s
                    └─sysinit.target @4.459s
                      └─systemd-udev-trigger.service @2.117s +2.327s
                        └─systemd-udevd-kernel.socket @866ms
                          └─-.slice @583ms

Enjoy!

**Comment by RaveGun** [comment]
Wow, this is really quick.

When do the steppers stop singing?

**Comment by manbehindthemadness** [comment]
That is relational to your board revision and micro step settings; however, it shouldn't be relational to any of the settings mentioned above.

**Comment by RaveGun** [comment]
Hm,

I think that yes, it has to do with the board revision, that the is a missing or weak pulldown on the stepper driver enable pin?

But the idea is that on an initial power on, this signal line floats and the steppers are ringing until the drivers got initialized. So the faster the redeem starts the better.

But I didn't started my printer in a whilev and maybe I am confusing the projects.

Thanks.

**Comment by eliasbakken** [comment]
I'm closing this issue since it is not actionable. If this is still relevant, it can either be documented on the wiki or a new issue posed as an enhancement or similar.
