### ISSUE TITLE
Touchscreen needs to be reconnected before matrix works[SOLUTION]

### ISSUE THREAD

**Issue by manbehindthemadness** [intelligent-agent/Refactor#107]
How to fix touch screens that need to be reconnected before registering touch data:
This functionality can be verified using evtest.

# build usbreset if it's not already present
cp /usr/src/Umikaze/Packages/USB/usbreset.c /bin
cd /bin
cc usbreset.c -o usbreset
chmod +x usbreset

# create reset service
cat <<EOT>> /lib/systemd/system/usbreset.service
[Unit]
Description=usbreset
Before=toggle.service

[Service]
Type=simple
ExecStart=/bin/sh /bin/usbreset.sh
KillMode=process

[Install]
WantedBy=toggle.service
EOT

# create executable that locates and resets the touch screen device
cat <<EOT>> /bin/usbreset.sh
DEVICE="$(dmesg |grep touch | head -1 | cut -d ':' -f 2,3 | cut -d '.' -f 1)"
DEV_BUS="$(lsusb | grep -i $DEVICE | cut -d ' ' -f 2)"
DEV_DEVICE="$(lsusb | grep -i $DEVICE | cut -d ' ' -f 4 | cut -d ':' -f 1)"
DEV_PATH='/dev/bus/usb/'$DEV_BUS'/'$DEV_DEVICE
echo 'resetting device: ' $DEV_PATH
/bin/usbreset $DEV_PATH
EOT

chmod +x /bin/usbreset.sh
systemctl enable usbreset.service

**Comment by eliasbakken** [comment]
Closing this since it is not actionable. We can open it up again if we want this as a part of Refactor for Replicape.
