### ISSUE TITLE
/etc/armbian-release has the wrong name

### ISSUE THREAD

**Issue by eliasbakken** [intelligent-agent/Refactor#121]
/etc/armbian-release has the wrong values for 
BOARD
and 
BOARD_NAME

Can be changes with the following one-liners: 
```
sed -i 's/Pine64/Recore/g' /mnt/etc/armbian-release
sed -i 's/pine64/recore/g' /mnt/etc/armbian-release
```

**Comment by goeland86** [comment]
Can also be done with an ansible task using the `replace` module... Advantage is that we can also add it to iterate over multiple files if you want to.
