### ISSUE TITLE
Clean up and move playbooks into separate folder

### ISSUE THREAD

**Issue by eliasbakken** [intelligent-agent/Refactor#124]
There are quite a few playbooks floating around in the root folder. These should be removed if they are no longer in use and those remaining should be placed in a separate folder.

**Comment by goeland86** [comment]
Actually they will be used - the point was to try and provide a number of playbooks that can be used to modify the existing image as needed, or to run upgrades, for example.

**Comment by eliasbakken** [comment]
Is "SYSTEM_redeem_octoprint-LEGACY.yml" still in use also? I think it would be good to have as little "clutter" as possible around to not confuse future users.

**Comment by goeland86** [comment]
That one isn't, no. We can move it to a legacy folder indeed.

Though I think Redeem may revive at some point - Klipper has certain a few limitations that we may eventually run into, and @ThatWileyGuy seemed quite attached to Redeem. I see no harm in maintaining a way to use ReFactor with Redeem in the long run.

**Comment by eliasbakken** [comment]
Sure! Would be great to revive it if Klipper has limitations or even for fun, but if it is not needed now we can simply delete it. We have it in the git history regardless.

**Comment by goeland86** [comment]
True. Wouldn't be hard to re-create from scratch either.

**Comment by eliasbakken** [comment]
It seems like it is not straight forward to place playbooks in separate folders. Though I'm not so sure about the pattern of having different playbooks for different scenarios, so we might want to look into that pattern.

**Comment by eliasbakken** [comment]
This was meerged with  PR #148
