### ISSUE TITLE
/home/debian not completely owned by user debian

### ISSUE THREAD

**Issue by eliasbakken** [intelligent-agent/Refactor#207]
Some folders are not completely owned by the user debian on the Refactor Recore image. 
A workaround is 
```chown -R debian:debian /home/debian```

**Comment by eliasbakken** [comment]
I tried to mount the partition on my laptop, but I think it might not be the best way to determine the ownership of the folders since my own user became the owner. It was consistent across all folders in /home/debian though, so I think we can say that this has been resolved.

**Comment by goeland86** [comment]
Look at the uid number instead of user assignment.

**Comment by eliasbakken** [comment]
UID is 1000, same as listed in /etc/passwd for debian.
