### ISSUE TITLE
Jenkins builds fail due to loop device being in use after unmount

### ISSUE THREAD

**Issue by goeland86** [intelligent-agent/Refactor#211]
The latest set of PR builds have failed to complete because of the following error:
```
+ echo 'Defragmenting partition mounted at /tmp/Refactor-sd.VR0D7U.'
Defragmenting partition mounted at /tmp/Refactor-sd.VR0D7U.
+ e4defrag -c /tmp/Refactor-sd.VR0D7U
+ umount -l /tmp/Refactor-sd.VR0D7U
+ echo

+ echo 'Resizing filesystem.'
Resizing filesystem.
+ e2fsck -f /dev/loop0p1 -y
e2fsck 1.45.7 (28-Jan-2021)
/dev/loop0p1 is in use.
e2fsck: Cannot continue, aborting.
```

This seems to be related to how the chroot is unmounted, and this needs to be fixed as the issue can randomly appear on any build system.

**Comment by eliasbakken** [comment]
Are you sure it's OK to force whatever program is using the file to be killed? It looks like it could have adverse effects that can be hard to track down.

**Comment by goeland86** [comment]
I'm pretty sure at the point where we're trying to unmount the partition, whatever is using it is not something that we want to keep running. I'm thinking the klipper service it something like it that got started by the ansible scripts that didn't stop for some reason.

**Comment by eliasbakken** [comment]
In all the cases you have changed, you are doing a defrag and mounting the the partition a couple of lines above it. How could that start any services?

**Comment by goeland86** [comment]
The crash was before the defrag started because it was not unmounted properly.
