### ISSUE TITLE
Create a plugin for OctoPrint that will allow updating, reinstalling, configuration etc. 

### ISSUE THREAD

**Issue by eliasbakken** [intelligent-agent/Refactor#217]

**Comment by goeland86** [comment]
And remove `kiauh` from the build script.

**Comment by eliasbakken** [comment]
A very basic plugin as been created that will get and display Refactor version and Klipper version in a tab on octoprint

**Comment by eliasbakken** [comment]
The plugin has support for showing which media is currently booted.

**Comment by eliasbakken** [comment]
Merged and tested in v3.0.2-RC2
