### ISSUE TITLE
Consider running klipper as Debian

### ISSUE THREAD

**Issue by eliasbakken** [intelligent-agent/Refactor#240]
Klipper is now running as user root. This might have security implications, and it is interfering with running 
Moonraker as user debian. 
If Klipper is run as root, it cannot call some of the startup-scripts that it needs to.

**Comment by eliasbakken** [comment]
It is possible to run klipper as user and run gpioget commands with sudo, so we should consider that.

**Comment by shuffleznl** [comment]
Config interactions (Save_variable and Save_config) make Klipper user (root) owner of files that are accessed/shared by processes (Moonraker/Octoklipper) from other users (debian).

**Comment by eliasbakken** [comment]
It would be good to remove the `gpioget` commands from the service file. A PR for that has been added to our fork of klipper

**Comment by eliasbakken** [comment]
Running Klipper as debian has been merged with PR #255
