### ISSUE TITLE
Debian password not set correctly

### ISSUE THREAD

**Issue by goeland86** [intelligent-agent/Refactor#270]
The original intended password for the `debian` user (meant to be `temppwd`) is no longer set to this value, refusing SSH logins on Recore.

This can be an issue if users want to login as a user and run commands as the same user as klipper or octoprint.

**Comment by eliasbakken** [comment]
Fixed by PR#270

**Comment by eliasbakken** [comment]
This is still a problem in v3.0.3-RC1.

**Comment by eliasbakken** [comment]
This is OK with RC2.
