### ISSUE TITLE
Moonraker-script: Printer.cfg location issue

### ISSUE THREAD

**Issue by shuffleznl** [intelligent-agent/Refactor#288]
[/home/debian/install-moonraker.sh](https://github.com/intelligent-agent/Refactor/blob/master/roles/install_moonraker/files/install-moonraker.sh) creates and links new printer_config folder (`/home/debian/printer_config`).
Having printer.cfg in that folder appears to be default behaviour for Moonraker (`/home/debian/printer_config/printer.cfg`). 

[/etc/systemd/system/klipper.service](https://github.com/intelligent-agent/Refactor/blob/master/roles/install_klipper/files/klipper.service) points to `/home/debian/printer.cfg`, causing klipper to fail to start

**Comment by eliasbakken** [comment]
I think we should probably use that folder for both moonraker and octoprint then.

**Comment by eliasbakken** [comment]
Merged with PR#297
