### ISSUE TITLE
Printer can not be shut down from Moonraker

### ISSUE THREAD

**Issue by eliasbakken** [intelligent-agent/Refactor#289]
It seems that the printer can not be shut down by using the control panel in moonraker. 
The message appearing in systemd journal is 
`Interactive authentication required`

**Comment by goeland86** [comment]
I think it's probably related to sudo permissions for the user that moonraker is running.

**Comment by eliasbakken** [comment]
A workaround is to run the Polkit script:
`su debian`
`cd /home/debian/moonraker/scripts`
`./set-policykit-rules.sh`

**Comment by eliasbakken** [comment]
This has been tested with PR#295, but since the stm32flash issue is a blocker, it is included in that PR.

**Comment by eliasbakken** [comment]
Merged in main
