### ISSUE TITLE
Numpy is missing from the klipper install

### ISSUE THREAD

**Issue by eliasbakken** [intelligent-agent/Refactor#290]
Numpy is needed to do adxl345 measurements, but it is not installed by default. 

A worksround is tun run:
`/home/debian/klippy-env/bin/pip install numpy`

**Comment by goeland86** [comment]
Maybe create a small utility script for those who want to install adxl345 support in the klipper repository's scripts folder? I believe upstream klipper will have the same possible issue.

**Comment by shuffleznl** [comment]
There are some other dependencies too which aren't in Refactor by default iirc: https://www.klipper3d.org/Measuring_Resonances.html

**Comment by eliasbakken** [comment]
Merged in main
