### ISSUE TITLE
Klipper shuts down during ADXL345 "TEST_RESONANCES AXIS=X" 

### ISSUE THREAD

**Issue by eliasbakken** [intelligent-agent/Refactor#291]
When running the command 
`TEST_RESONANCES AXIS=X`
on a printer with ADXL345 installed, Klipper shuts down with the message 
`MCU 'ar100' shutdown: Timer too close`

**Comment by eliasbakken** [comment]
I tried to increase the dynmem_pool size frmo 8K to 16K without any noticeable difference.

**Comment by Avatarsia** [comment]
maybe it's an issue with the script, cuz it's written for a rpi ?

**Comment by eliasbakken** [comment]
I've tested this with a lower rate and it seems to work fine at `rate: 400`. 
I've also tested it with a Pi Pico witch is an alternative. The wiki has been updated, so I'm closing this issue.
