### ISSUE TITLE
Klipper shuts down during ADXL345 when BL Touch is connected on Endstop Pins

### ISSUE THREAD

**Issue by Avatarsia** [intelligent-agent/Refactor#292]
As Soon you start to request Anything from the ADXL like Noice the AR100 will produce a shutdown. 
When disconnect the BL the noice request will work.

[bltouch]
sensor_pin: ^ar100:PH6
control_pin: !PB3
x_offset:29.2
y_offset:-34
#z_offset:0
speed:15
samples:1
pin_move_time: 0.675
sample_retract_dist: 10
#set_output_mode: 5V
probe_with_touch_mode: true
stow_on_each_sample: false

[adxl345]
cs_pin: ar100:PL11
spi_software_sclk_pin: ar100:PL10
spi_software_mosi_pin: ar100:PE15
spi_software_miso_pin: ar100:PE14

[resonance_tester]
accel_chip: adxl345
probe_points:
    150, 150, 20  # an example

**Comment by eliasbakken** [comment]
This is not really a BLTouch issue, but an ADXL345 issue when using that chip with the `soft spi`. I've tested this with a working BLTouch setup and when setting `rate:400` on the adxl345 it works fine.
