### ISSUE TITLE
Running `apt upgrade` fails for v3.0.3

### ISSUE THREAD

**Issue by eliasbakken** [intelligent-agent/Refactor#302]
Because the /boot partition is read only, running `apt upgrade` fails. 

In order for it to complete, the boot partition will have to be remounted as read-write:
`mount -o remount,rw /boot`
It looks like the `/boot/dtb/` folder is removed during the upgrade, so it's a good idea to back up the recore device trees:
`mkdir /opt/backup`
`cp /boot/dtb/allwinner/sun50i-a64-recore* /opt/backup/`
After the upgrade, the files should be copied back: 
`cp /opt/backup/sun50i-a64-recore* /boot/dtb/allwinner/ `

**Comment by Avatarsia** [comment]
remember the backlink

**Comment by eliasbakken** [comment]
In v3.2.0, there is now a possibility to update the system from Mainsail.
