### ISSUE TITLE
Create a separate image with Moonraker, Mainsail and KlipperScreen

### ISSUE THREAD

**Issue by eliasbakken** [intelligent-agent/Refactor#307]
There are now scripts available for installing Moonraker, Mainsail and KlipperScreen, but it is time consuming to run the scripts on Recore. Instead, we could create a new distro that has the necessary files and configs installed.

**Comment by eliasbakken** [comment]
PR created. Needs testing before merge.

**Comment by eliasbakken** [comment]
Tested both Mainsail and OctoPrint.

**Comment by Jasontwd** [comment]
Keen on this please.  Cheers Jason
