### ISSUE TITLE
BUG, after reflash on recore from USB to eMMc with latest mainsail image file

### ISSUE THREAD

**Issue by Jasontwd** [intelligent-agent/Refactor#318]
Hi Guys,
Sorry, new to reporting bugs, hope this makes sense
Using the latest image:
https://github.com/intelligent-agent/Refactor/releases/tag/v3.1.0-RC0

Using this as instructions:
https://wiki.iagent.no/wiki/Refactor -> Upgrading Refactor from the command line. You're already running from USB I think so you can skip to the second command immediately

Problem found:
did wget [the new file]
the old firmware is still on eMMc and still as klipper server script errors
but reads:
v3.1.0-RC0

Comment from @geoland86
yeah, it should be in /etc/refactor.version
this is my current installation:
root@recore:~# cat /etc/refactor.version
v3.0.3-RC5v3.0.3
 2022-02-19root@recore:~#
As you can see, a bit behind on the times
If yours reads v3.1.0-RC0, then we know the image created by @elias has a probable bug in it

**Comment by Jasontwd** [comment]
<img width="559" alt="image" src="https://user-images.githubusercontent.com/25860987/174460822-a30f5ea6-50ff-4691-bc4f-9466531d5827.png">

**Comment by eliasbakken** [comment]
Hi, I'm not sure what has happened here, but it looks like something has gone wrong during the flashing. Could you try the instructions explained in the Reflash image? http://feeds.iagent.no/images/reflash/

**Comment by eliasbakken** [comment]
Instructions here: https://wiki.iagent.no/wiki/Reflash
