### ISSUE TITLE
The flashing script on 3.1.0-RC0 is broken

### ISSUE THREAD

**Issue by pzemlyan** [intelligent-agent/Refactor#319]
The current image (Refactor-recore-mainsail-v3.1.0-RC0-2022-06-11) does not contains "pv" utility which is necessary to run flash-recore script.

No error message displayed.

apt-get helps, still

**Comment by Avatarsia** [comment]
sudo apt-get install pv

should help

**Comment by eliasbakken** [comment]
The method of using Refactor running on a USB drive to install Refactor is probably going to be phased out in favor of having a separate "flasher" image that can be used to flash Refactor. 
The first version is available here: http://feeds.iagent.no/images/reflash/

**Comment by Avatarsia** [comment]
> The method of using Refactor running on a USB drive to install Refactor is probably going to be phased out in favor of having a separate "flasher" image that can be used to flash Refactor. The first version is available here: http://feeds.iagent.no/images/reflash/

pleae be more precize with the commands to install and run this image ome small issues on that page

**Comment by eliasbakken** [comment]
pv is now installed in the image that is in the master branch. Closing this.
