### ISSUE TITLE
3.1.0-RC0 - Mainsail Image - apt upgrade

### ISSUE THREAD

**Issue by Avatarsia** [intelligent-agent/Refactor#321]
upt- upgrade will fail based on a kernel update - this will need a backup of the files and a copy back, otherwise the system need a reflash via fel

**Comment by eliasbakken** [comment]
I've disabled system upgrades for now until we can find a way to override the "apt upgrade" system call.

**Comment by eliasbakken** [comment]
There is now a script in `/usr/local/lib` called `refactor-apt-upgrade` that gives a way to do a safe system upgrade.

**Comment by eliasbakken** [comment]
I think we should close this issue and instead add a new issue that better reflects the current state for system updates.
