### ISSUE TITLE
3.1.0-RC0 - moonraker image - Git Pull not available / damaged versions from interface

### ISSUE THREAD

**Issue by Avatarsia** [intelligent-agent/Refactor#323]
updates for klipper and moonraker are shown as damaged or incompatible 
git pull is not available for moonraker via ssh

**Comment by eliasbakken** [comment]
Both klipper and moonraker show up with status "unknown". It might be due to the "depth: 1" directive in ansible. Needs some more investigation.

**Comment by Avatarsia** [comment]
in my last state i checked there was no git source given for moonraker - thats why it's unknowen

**Comment by eliasbakken** [comment]
![mainsail](https://user-images.githubusercontent.com/3756249/180624809-837014f0-3205-4024-ac42-3f7dc72be877.png)
Fixed in latest master
