### ISSUE TITLE
Improvement - Board Fan Control by Temperature

### ISSUE THREAD

**Issue by Avatarsia** [intelligent-agent/Refactor#324]
Change to default the Board Temperature to a fan control, this will also be shown in the chart

[temperature_fan board]
pin: PB4
min_temp: 20
max_temp: 100
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PA6
control: watermark
gcode_id: Board
target_temp: 75

**Comment by Avatarsia** [comment]
![image](https://user-images.githubusercontent.com/43354003/179748323-60d26ebe-e78a-43cd-8900-f3a96666aa5e.png)

**Comment by Avatarsia** [comment]
Red is te complete view of that board temperature
Blue is the current Temperature of the board
Green is the target temperature where the fan switch on/off

**Comment by eliasbakken** [comment]
This has been added to the config in Klipper

**Comment by eliasbakken** [comment]
Merged in master
