### ISSUE TITLE
Create a repository for temporary images

### ISSUE THREAD

**Issue by goeland86** [intelligent-agent/Refactor#327]
The plan is to make non-tagged images accessible for testing by advanced users.

1. Modify the Github Actions workflows to upload the non-tagged image by SCP to a server
2. Make the uploaded images available through a simple webpage (ideally named after the branch and date of the build)
3. Have the temporary images be removed every 7 or 14 days, depending on what turns out to be the appropriate timeline.

**Comment by eliasbakken** [comment]
I have a script to download and publish new images. I don't have enough knowledge about security to automate this to publish on a server automatically, so I think it's better to do it manually for now. The images are uploaded to: 
http://feeds.iagent.no/images/Refactor/
