### ISSUE TITLE
Activity/progress indicator during flashing/dd

### ISSUE THREAD

**Issue by shuffleznl** [intelligent-agent/Refactor#348]
Upon running `flash-recore` there is no indication of activity after the unmounting of mmcblk0p1 partition.
A screen clear, 'Are You Sure-prompt' and then `Flashing now` (or `Writing Image`) indication would be welcome (since depending on USB-speed it can take a while).

**Comment by eliasbakken** [comment]
Since we now have a dedicated image for flashing, this issue is not relevant here. It used to be that flashing was done from Refactor, but is now done by Reflash. If it's interesting to have a better command line user interface for flashing, this issue can be opened in the Reflash repository.
