### ISSUE TITLE
Armbian ansible version too old

### ISSUE THREAD

**Issue by goeland86** [intelligent-agent/Refactor#373]
The Armbian ansible version is very old (2.7.7) compared to the latest version available (2.9+).

The syntax has changed, and a number of performance improvements will be available from newer versions as well.

Change the Ansible installation method to use pip instead of apt-get, to use the latest version.

**Comment by eliasbakken** [comment]
The installed Ansible version in Bullseye is 2.10.7, so I think we can call this fixed.
