### ISSUE TITLE
Weston cannot be restarted by systemd.

### ISSUE THREAD

**Issue by goeland86** [intelligent-agent/Refactor#375]
Weston seems to have an issue on Refactor since 3.1.3, where using systemctl stop doesn't kill it, and systemctl restart doesn't actually restart Weston, but starts a second instance.

If weston is manually stopped (with `kill`), then systemctl still cannot start a new instance correctly. This is especially annoying when dealing with screen rotation settings, as a full reboot seems to be necessary.

**Comment by eliasbakken** [comment]
Weston can be restarted in the normal way in the latest version (v3.2.0-RC2).
