### ISSUE TITLE
could this just be used on a computer to be used lika a raspberry pi?

### ISSUE THREAD

**Issue by Mustangkinsey** [intelligent-agent/Refactor#380]

**Comment by goeland86** [comment]
In theory yes, but in practice the suite installs different sets of requirements to interface with different hardware.

If you want to make it "desktop" or raspberry pi friendly, in the various roles folders, under tasks you'll see yaml files. If you create one for pi in each role, you can then create an image for raspberry pi. Similarly if we create one for PC, it could run on PC as well. We just need to use a different baselinux fine for each CPU architecture.
