### ISSUE TITLE
Grab Replicape overlay from RCN repos

### ISSUE THREAD

**Issue by goeland86** [intelligent-agent/Refactor#55]
Instead of grabbing from the bitbucket repo, grab the overlay from RCN's repo directly.

**Comment by goeland86** [comment]
Instead grabbing the repo from @ThatWileyGuy since the PR was not yet merged by RCN.

**Comment by Wackerbarth** [comment]
If RCN isn't always up to date, we should fork the repo into `intelligent-agent` so that we are assured that whatever version we are using for the build is always available.

**Comment by eliasbakken** [comment]
Replicape overlays are now present in RCN repos.
