### ISSUE TITLE
Importing local.cfg for toggle into OctoPrint to wrong location

### ISSUE THREAD

**Issue by fiveofds** [intelligent-agent/Refactor#62]
When I import local.cfg for toggle it shows up under printer.cfg and not Profiles.
This prevents me from being able to edit the local.cfg in OctoPrint and I have to use an external editor then re-import it.

**Comment by goeland86** [comment]
I think this may need to go to intelligent-agent/toggle instead, but it was filed here.

**Comment by eliasbakken** [comment]
/etc/toggle/local.cfg is created by ansible and should be OK now.
