### ISSUE TITLE
BBBW Connection

### ISSUE THREAD

**Issue by OCD3DP** [intelligent-agent/Refactor#78]
I flashed 2.2.0 rc3 on my BBBW this morning and could not get connected to the board using Windows 10 or Ubuntu. Is there something I’m missing? Could the BBBW be configured as an access point to make things easier?

**Comment by Wackerbarth** [comment]
I don't have the hardware resources to investigate this.

**Comment by goeland86** [comment]
My bad @Wackerbarth - I forgot. I'll ask @ThatWileyGuy to help me figure this out.

**Comment by eliasbakken** [comment]
I think this issue is too old to do anything with at this point. I'm closing it.
