### ISSUE TITLE
Build script includes kernel-related files that have nothing to do with the desired TARGET kernel

### ISSUE THREAD

**Issue by Wackerbarth** [intelligent-agent/Refactor#84]
@goeland86  -- "As to the kernel update issue. The apt-get scripts detect they're running in a chroot and only update based on what's in the available filesystem, without depending on the running kernel at all."

Then please explain why we end up with a bunch of "extra" initrd images, etc.

And note the following excerpt from the build log:

```
Setting up socat (1.7.3.1-1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for initramfs-tools (0.122ubuntu8.13) ...
update-initramfs: Generating /boot/initrd.img-4.15.7-armv7-x1
modinfo: ERROR: Module /lib/modules/4.15.7-armv7-x1/kernel/fs/isofs/isofs.ko.xz not found.
modinfo: ERROR: Module /lib/modules/4.15.7-armv7-x1/kernel/fs/jfs/jfs.ko.xz not found.
```
Yes, `/boot/initrd.img-4.15.7-armv7-x1` is just one of those "extra" files that get created.

**Comment by goeland86** [comment]
Well I can't speak to what your host system is like. Normally the update kernel script from RCN should make sure only a single initrd is left in the boot folder.
